#define _POSIX_C_SOURCE 200809L
#include <errno.h>
#include <inttypes.h>
#include <limits.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct { int64_t n; uint8_t e; uint8_t valid; } Surr;
static Surr bad(void){ Surr x={0,0,0}; return x; }
static Surr norm(int64_t n,unsigned e){ if(e>62)return bad(); while(e&&!(n&1)){n/=2;e--;} Surr x={n,(uint8_t)e,1};return x; }
static int scale(Surr x,unsigned e,int64_t *o){ unsigned d=e-x.e; __int128 z=(__int128)x.n*((__int128)1<<d); if(z>INT64_MAX||z<INT64_MIN)return 0;*o=(int64_t)z;return 1; }
static Surr sadd(Surr a,Surr b){ if(!a.valid||!b.valid)return bad();unsigned e=a.e>b.e?a.e:b.e;int64_t x,y;if(!scale(a,e,&x)||!scale(b,e,&y))return bad();__int128 z=(__int128)x+y;if(z>INT64_MAX||z<INT64_MIN)return bad();return norm((int64_t)z,e); }
static Surr smul(Surr a,Surr b){ if(!a.valid||!b.valid||a.e+b.e>62)return bad();__int128 z=(__int128)a.n*b.n;if(z>INT64_MAX||z<INT64_MIN)return bad();return norm((int64_t)z,a.e+b.e); }
static int scmp(Surr a,Surr b,int *o){ if(!a.valid||!b.valid)return 0;unsigned e=a.e>b.e?a.e:b.e;__int128 x=(__int128)a.n*((__int128)1<<(e-a.e)),y=(__int128)b.n*((__int128)1<<(e-b.e));*o=(x>y)-(x<y);return 1; }
static void sprint(FILE*f,Surr x){if(!x.valid)fputs("unresolved",f);else fprintf(f,"%"PRId64"/2^%u",x.n,x.e);}

enum { OP_PUSH=1,OP_ADD,OP_MUL,OP_NEG,OP_DUP,OP_PRINT,OP_EMIT,OP_PIXEL,OP_RECT,OP_CLEAR,OP_CAINA,OP_HALT,
 OP_SUB,OP_DROP,OP_SWAP,OP_EQ,OP_LT,OP_GT,OP_JUMP,OP_JZ,OP_JNZ,OP_CALL,OP_RET,OP_LOADV,OP_STOREV,OP_MLOAD,OP_MSTORE,OP_ANTENORA,OP_JUDECCA,OP_SOURCEBYTE };
typedef struct { uint8_t op,e; uint16_t pad; int64_t a,b,c,d,k; } Ins;
typedef struct { Ins *v; size_t n,cap; } Prog;
typedef struct { char name[32]; uint64_t ip; } Symbol;
typedef struct { char name[32]; size_t at; unsigned line; } Fixup;
static int addins(Prog*p,Ins x){if(p->n==p->cap){size_t z=p->cap?p->cap*2:64;void*q=realloc(p->v,z*sizeof x);if(!q)return 0;p->v=q;p->cap=z;}p->v[p->n++]=x;return 1;}
static char* trim(char*s){while(*s==' '||*s=='\t')s++;char*e=s+strlen(s);while(e>s&&(e[-1]==' '||e[-1]=='\t'||e[-1]=='\r'||e[-1]=='\n'))*--e=0;return s;}
#define G(a,b,c,d,e,f,g) ((uint64_t)(a)|((uint64_t)(b)<<5)|((uint64_t)(c)<<10)|((uint64_t)(d)<<15)|((uint64_t)(e)<<20)|((uint64_t)(f)<<25)|((uint64_t)(g)<<30))
static uint64_t glyph(int c){switch(c){
 case 'A':return G(14,17,17,31,17,17,17);case 'B':return G(30,17,17,30,17,17,30);case 'C':return G(14,17,16,16,16,17,14);case 'D':return G(30,17,17,17,17,17,30);
 case 'E':return G(31,16,16,30,16,16,31);case 'F':return G(31,16,16,30,16,16,16);case 'G':return G(14,17,16,23,17,17,15);case 'H':return G(17,17,17,31,17,17,17);
 case 'I':return G(31,4,4,4,4,4,31);case 'J':return G(7,2,2,2,18,18,12);case 'K':return G(17,18,20,24,20,18,17);case 'L':return G(16,16,16,16,16,16,31);
 case 'M':return G(17,27,21,21,17,17,17);case 'N':return G(17,25,21,19,17,17,17);case 'O':return G(14,17,17,17,17,17,14);case 'P':return G(30,17,17,30,16,16,16);
 case 'Q':return G(14,17,17,17,21,18,13);case 'R':return G(30,17,17,30,20,18,17);case 'S':return G(15,16,16,14,1,1,30);case 'T':return G(31,4,4,4,4,4,4);
 case 'U':return G(17,17,17,17,17,17,14);case 'V':return G(17,17,17,17,17,10,4);case 'W':return G(17,17,17,21,21,21,10);case 'X':return G(17,17,10,4,10,17,17);
 case 'Y':return G(17,17,10,4,4,4,4);case 'Z':return G(31,1,2,4,8,16,31);
 case '0':return G(14,17,19,21,25,17,14);case '1':return G(4,12,4,4,4,4,14);case '2':return G(14,17,1,2,4,8,31);case '3':return G(30,1,1,14,1,1,30);
 case '4':return G(2,6,10,18,31,2,2);case '5':return G(31,16,16,30,1,1,30);case '6':return G(14,16,16,30,17,17,14);case '7':return G(31,1,2,4,8,8,8);
 case '8':return G(14,17,17,14,17,17,14);case '9':return G(14,17,17,15,1,1,14);
 case '-':return G(0,0,0,31,0,0,0);case '_':return G(0,0,0,0,0,0,31);case '.':return G(0,0,0,0,0,12,12);case ':':return G(0,12,12,0,12,12,0);
 case '/':return G(1,2,2,4,8,8,16);case '+':return G(0,4,4,31,4,4,0);case '=':return G(0,0,31,0,31,0,0);case '>':return G(16,8,4,2,4,8,16);
 case '[':return G(14,8,8,8,8,8,14);case ']':return G(14,2,2,2,2,2,14);case '(':return G(2,4,8,8,8,4,2);case ')':return G(8,4,2,2,2,4,8);
 default:return 0;}}
static int addtext(Prog*p,int64_t x,int64_t y,int64_t scale,int64_t color,const char*s){if(scale<1||scale>8)return 0;for(;*s;s++,x+=6*scale){int c=(unsigned char)*s;if(c>='a'&&c<='z')c-=32;uint64_t g=glyph(c);for(int r=0;r<7;r++)for(int q=0;q<5;q++)if((g>>(r*5+4-q))&1){Ins z={.op=OP_RECT,.a=x+q*scale,.b=y+r*scale,.c=scale,.d=scale,.k=color};if(!addins(p,z))return 0;}}return 1;}
static int nameok(const char*s){size_t n=strlen(s);if(!n||n>31)return 0;for(size_t i=0;i<n;i++)if(!((s[i]>='a'&&s[i]<='z')||(s[i]>='A'&&s[i]<='Z')||(i&&s[i]>='0'&&s[i]<='9')||s[i]=='_'))return 0;return 1;}
static int findsym(Symbol*s,size_t n,const char*name){for(size_t i=0;i<n;i++)if(!strcmp(s[i].name,name))return(int)i;return-1;}
static int compile_source(const char*in,const char*out){
 FILE*f=fopen(in,"r");if(!f){perror(in);return 1;}Prog p={0};Symbol labels[512],vars[256];Fixup fixes[2048];size_t nl=0,nv=0,nf=0;char line[1024];unsigned ln=0;int fail=0;
 uint64_t image_count=UINT64_MAX;
 while(fgets(line,sizeof line,f)){ln++;char*s=trim(line);if(!*s||*s=='#')continue;char op[32]={0},name[32]={0},extra=0;long long a=0,b=0,c=0,d=0,e=0;int k=sscanf(s,"%31s %lld %lld %lld %lld %lld",op,&a,&b,&c,&d,&e);Ins x={0};
  if(!strcmp(op,"image")){unsigned long long q=0;if(sscanf(s,"image %llu %c",&q,&extra)!=1||image_count!=UINT64_MAX){fail=1;fprintf(stderr,"%s:%u: invalid or duplicate image declaration\n",in,ln);break;}image_count=(uint64_t)q;continue;}
  if(!strcmp(op,"native")){long long no=0,ne=0,na=0,nb=0,nc=0,nd=0,nk=0;if(sscanf(s,"native %lld %lld %lld %lld %lld %lld %lld %c",&no,&ne,&na,&nb,&nc,&nd,&nk,&extra)!=7||no<1||no>OP_SOURCEBYTE||ne<0||ne>255){fail=1;fprintf(stderr,"%s:%u: invalid canonical instruction\n",in,ln);break;}x.op=(uint8_t)no;x.e=(uint8_t)ne;x.a=na;x.b=nb;x.c=nc;x.d=nd;x.k=nk;if(!addins(&p,x)){fail=1;break;}continue;}
  if(!strcmp(op,"label")||!strcmp(op,"func")||!strcmp(op,"ptolomaea")){if(sscanf(s,"%*s %31s %c",name,&extra)!=1||!nameok(name)||nl==512||findsym(labels,nl,name)>=0){fail=1;}else{strcpy(labels[nl].name,name);labels[nl++].ip=p.n;}if(fail)fprintf(stderr,"%s:%u: invalid or duplicate label\n",in,ln);continue;}
  if(!strcmp(op,"var")){if(sscanf(s,"var %31s %lld %lld %c",name,&a,&b,&extra)!=3||!nameok(name)||nv==256||findsym(vars,nv,name)>=0||b<0||b>62){fail=1;fprintf(stderr,"%s:%u: invalid or duplicate variable\n",in,ln);break;}strcpy(vars[nv].name,name);vars[nv].ip=nv;x.op=OP_PUSH;x.a=a;x.e=(uint8_t)b;if(!addins(&p,x)){fail=1;break;}x=(Ins){.op=OP_STOREV,.a=(int64_t)nv++};if(!addins(&p,x)){fail=1;break;}continue;}
  if(!strcmp(op,"push")&&k==3){x.op=OP_PUSH;x.a=a;x.e=(uint8_t)b;if(b<0||b>62)fail=1;}
  else if(!strcmp(op,"add")&&k==1)x.op=OP_ADD;else if(!strcmp(op,"sub")&&k==1)x.op=OP_SUB;else if(!strcmp(op,"mul")&&k==1)x.op=OP_MUL;
  else if(!strcmp(op,"neg")&&k==1)x.op=OP_NEG;else if(!strcmp(op,"dup")&&k==1)x.op=OP_DUP;else if(!strcmp(op,"drop")&&k==1)x.op=OP_DROP;else if(!strcmp(op,"swap")&&k==1)x.op=OP_SWAP;
  else if(!strcmp(op,"eq")&&k==1)x.op=OP_EQ;else if(!strcmp(op,"lt")&&k==1)x.op=OP_LT;else if(!strcmp(op,"gt")&&k==1)x.op=OP_GT;
  else if(!strcmp(op,"print")&&k==1)x.op=OP_PRINT;else if(!strcmp(op,"emit")&&k==1)x.op=OP_EMIT;else if((!strcmp(op,"read")||!strcmp(op,"antenora"))&&k==1)x.op=OP_ANTENORA;else if(!strcmp(op,"sourcebyte")&&k==1)x.op=OP_SOURCEBYTE;
  else if(!strcmp(op,"mload")&&k==1)x.op=OP_MLOAD;else if(!strcmp(op,"mstore")&&k==1)x.op=OP_MSTORE;
  else if((!strcmp(op,"ret")||!strcmp(op,"return"))&&k==1)x.op=OP_RET;
  else if(!strcmp(op,"jump")||!strcmp(op,"jz")||!strcmp(op,"jnz")||!strcmp(op,"call")){if(sscanf(s,"%*s %31s %c",name,&extra)!=1||!nameok(name)||nf==2048){fail=1;}else{x.op=!strcmp(op,"jump")?OP_JUMP:!strcmp(op,"jz")?OP_JZ:!strcmp(op,"jnz")?OP_JNZ:OP_CALL;strcpy(fixes[nf].name,name);fixes[nf].at=p.n;fixes[nf++].line=ln;} }
  else if(!strcmp(op,"load")||!strcmp(op,"store")){if(sscanf(s,"%*s %31s %c",name,&extra)!=1){fail=1;}else{int vi=findsym(vars,nv,name);if(vi<0)fail=1;else{x.op=!strcmp(op,"load")?OP_LOADV:OP_STOREV;x.a=vi;}}}
  else if(!strcmp(op,"pixel")&&k==4){x.op=OP_PIXEL;x.a=a;x.b=b;x.c=c;}
  else if(!strcmp(op,"rect")&&k==6){x.op=OP_RECT;x.a=a;x.b=b;x.c=c;x.d=d;x.k=e;}
  else if(!strcmp(op,"text")){int pos=0;if(sscanf(s,"text %lld %lld %lld %lld %n",&a,&b,&c,&d,&pos)!=4||!addtext(&p,a,b,c,d,s+pos))fail=1;else continue;}
  else if(!strcmp(op,"clear")&&k==2){x.op=OP_CLEAR;x.a=a;}
  else if((!strcmp(op,"caina")||!strcmp(op,"barrier"))&&k==1)x.op=OP_CAINA;
  else if((!strcmp(op,"judecca")||!strcmp(op,"frost"))&&k==3){x.op=OP_JUDECCA;x.a=a;x.b=b;if(a<0||a>=65536||b<1)fail=1;}
  else if(!strcmp(op,"halt")&&k==1)x.op=OP_HALT;
  else fail=1;
  if(fail){fprintf(stderr,"%s:%u: invalid instruction: %s\n",in,ln,s);break;}if(!addins(&p,x)){fail=1;break;}
 }
 fclose(f);for(size_t i=0;!fail&&i<nf;i++){int li=findsym(labels,nl,fixes[i].name);if(li<0){fprintf(stderr,"%s:%u: undefined label: %s\n",in,fixes[i].line,fixes[i].name);fail=1;}else p.v[fixes[i].at].a=(int64_t)labels[li].ip;}if(!fail&&image_count!=UINT64_MAX&&image_count!=p.n){fprintf(stderr,"%s: image count mismatch declared=%"PRIu64" actual=%zu\n",in,image_count,p.n);fail=1;}
 if(fail){free(p.v);return 2;}FILE*g=fopen(out,"wb");if(!g){perror(out);free(p.v);return 1;}uint8_t h[16]={'C','O','C','1',1,0,0,0};uint64_t n=p.n;memcpy(h+8,&n,8);int ok=fwrite(h,1,16,g)==16&&fwrite(p.v,sizeof(Ins),p.n,g)==p.n&&!fclose(g);free(p.v);return ok?0:1;
}

static int canonicalize(const char*in,const char*out){FILE*f=fopen(in,"rb");if(!f){perror(in);return 1;}uint8_t h[16];if(fread(h,1,16,f)!=16||memcmp(h,"COC1",4)||h[4]!=1){fprintf(stderr,"invalid COC1 bytecode\n");fclose(f);return 2;}uint64_t n=0;memcpy(&n,h+8,8);if(n>1000000){fclose(f);return 2;}FILE*g=fopen(out,"wb");if(!g){perror(out);fclose(f);return 1;}int ok=fprintf(g,"# Canonical Cocytus compiler source. The numeric records are the quine fixed point.\nimage %"PRIu64"\n",n)>0;for(uint64_t i=0;ok&&i<n;i++){Ins x;if(fread(&x,sizeof x,1,f)!=1){ok=0;break;}ok=fprintf(g,"native %u %u %"PRId64" %"PRId64" %"PRId64" %"PRId64" %"PRId64"\n",x.op,x.e,x.a,x.b,x.c,x.d,x.k)>0;}if(ok)ok=fgetc(f)==EOF&&!ferror(f);if(fclose(f))ok=0;if(fclose(g))ok=0;return ok?0:1;}

#define W 640
#define H 400
static uint32_t canvas[W*H];
static void clearc(uint32_t c){for(size_t i=0;i<W*H;i++)canvas[i]=c;}
static void rectc(int x,int y,int w,int h,uint32_t c){if(w<0){x+=w;w=-w;}if(h<0){y+=h;h=-h;}for(int j=0;j<h;j++)for(int i=0;i<w;i++){int xx=x+i,yy=y+j;if(xx>=0&&xx<W&&yy>=0&&yy<H)canvas[yy*W+xx]=c;}}
static int ppm(const char*path){FILE*f=fopen(path,"wb");if(!f)return 0;fprintf(f,"P6\n%d %d\n255\n",W,H);for(size_t i=0;i<W*H;i++){uint8_t b[3]={(uint8_t)(canvas[i]>>16),(uint8_t)(canvas[i]>>8),(uint8_t)canvas[i]};if(fwrite(b,1,3,f)!=3){fclose(f);return 0;}}return !fclose(f);}
static int frameppm(const char*prefix,uint64_t index){char path[PATH_MAX];if(snprintf(path,sizeof path,"%s-%06"PRIu64".ppm",prefix,index)>=(int)sizeof path)return 0;return ppm(path);}
static uint8_t awarp(uint8_t raw){return(uint8_t)(3u*(unsigned)raw+1u);}
static uint8_t aunwarp(uint8_t warped){return(uint8_t)(171u*(unsigned)(uint8_t)(warped-1u));}

/* X11 ABI declarations: the shipped executable talks directly to the host window ABI. */
typedef struct _XDisplay Display;typedef unsigned long Window,GC,Time,KeySym;typedef struct{int type;unsigned long serial;int send_event;Display*display;Window window,root,subwindow;Time time;int x,y,x_root,y_root;unsigned state,keycode;int same_screen;}XKeyEvent;typedef struct{int type;unsigned long serial;int send_event;Display*display;Window window,root,subwindow;Time time;int x,y,x_root,y_root;unsigned state,button;int same_screen;}XButtonEvent;typedef union{int type;long pad[24];XKeyEvent xkey;XButtonEvent xbutton;}XEvent;
extern Display*XOpenDisplay(const char*);extern int XCloseDisplay(Display*);extern int XDefaultScreen(Display*);extern Window XRootWindow(Display*,int);extern unsigned long XBlackPixel(Display*,int),XWhitePixel(Display*,int);extern Window XCreateSimpleWindow(Display*,Window,int,int,unsigned,unsigned,unsigned,unsigned long,unsigned long);extern int XStoreName(Display*,Window,const char*),XSelectInput(Display*,Window,long),XMapWindow(Display*,Window),XNextEvent(Display*,XEvent*),XFlush(Display*),XDestroyWindow(Display*,Window);extern GC XCreateGC(Display*,Window,unsigned long,void*);extern int XSetForeground(Display*,GC,unsigned long),XFillRectangle(Display*,Window,GC,int,int,unsigned,unsigned),XDrawString(Display*,Window,GC,int,int,const char*,int),XFreeGC(Display*,GC),XLookupString(XKeyEvent*,char*,int,KeySym*,void*);
static int runbc(const char*,const char*,int,const char*);
static void xpaint(Display*d,Window w,GC gc,const char*src,const char*status){for(int y=0;y<H;y++){int x=0;while(x<W){uint32_t c=canvas[y*W+x];int q=x+1;while(q<W&&canvas[y*W+q]==c)q++;XSetForeground(d,gc,c);XFillRectangle(d,w,gc,x,y,(unsigned)(q-x),1);x=q;}}if(src){XSetForeground(d,gc,0x080d18);XFillRectangle(d,w,gc,184,68,310,246);XSetForeground(d,gc,0xa9b9d6);const char*p=src;int line=0;while(*p&&line<20){const char*e=strchr(p,'\n');size_t n=e?(size_t)(e-p):strlen(p);if(n>48)n=48;char b[49];memcpy(b,p,n);b[n]=0;XDrawString(d,w,gc,194,82+line*11,b,(int)n);line++;if(!e)break;p=e+1;}XSetForeground(d,gc,0x111c31);XFillRectangle(d,w,gc,0,316,640,66);XSetForeground(d,gc,0x42e6a4);XDrawString(d,w,gc,12,342,status,(int)strlen(status));const char*hint="TYPE SOURCE   BUILD CLICK / CTRL-S   RUN CLICK / CTRL-R   ESC CLOSE";XSetForeground(d,gc,0x65d9ff);XDrawString(d,w,gc,12,360,hint,(int)strlen(hint));}XFlush(d);}
static int studiosave(const char*path,const char*b,size_t n){FILE*f=fopen(path,"wb");if(!f)return 0;int ok=fwrite(b,1,n,f)==n&&!fclose(f);return ok;}
static int showx(const char*source){char*edit=NULL;size_t len=0,cap=32768;char out[PATH_MAX];int interactive=source!=NULL,built=0;const char*status=interactive?"READY - EDITING REAL COCYTUS SOURCE":"RUN COMPLETE - ESC CLOSE";if(interactive){edit=calloc(cap,1);if(!edit)return 0;FILE*f=fopen(source,"rb");if(!f){free(edit);return 0;}len=fread(edit,1,cap-1,f);if(ferror(f)){fclose(f);free(edit);return 0;}fclose(f);size_t sn=strlen(source);if(sn>=4&&!strcmp(source+sn-4,".coc")){if(sn+1>sizeof out){free(edit);return 0;}memcpy(out,source,sn-4);memcpy(out+sn-4,".cob",5);}else if(snprintf(out,sizeof out,"%s.cob",source)>=(int)sizeof out){free(edit);return 0;}if(compile_source(source,out)||runbc(out,NULL,0,NULL)){free(edit);return 0;}built=1;}Display*d=XOpenDisplay(NULL);if(!d){free(edit);return 0;}int s=XDefaultScreen(d),done=0;Window w=XCreateSimpleWindow(d,XRootWindow(d,s),40,40,W,H,1,XWhitePixel(d,s),XBlackPixel(d,s));XStoreName(d,w,interactive?"Cocytus 0.2.1 Studio":"Cocytus Frozen Canvas");XSelectInput(d,w,(1L<<15)|(1L<<0)|(1L<<2));XMapWindow(d,w);GC gc=XCreateGC(d,w,0,NULL);while(!done){XEvent e;XNextEvent(d,&e);if(e.type==12)xpaint(d,w,gc,edit,status);else if(e.type==2){KeySym ks=0;char b[32];int n=XLookupString(&e.xkey,b,sizeof b,&ks,NULL);int build=(e.xkey.state&4u)&&n==1&&(b[0]=='s'||b[0]=='S'),run=(e.xkey.state&4u)&&n==1&&(b[0]=='r'||b[0]=='R');if(ks==0xff1b)done=1;else if(interactive&&(build||run)){if(!studiosave(source,edit,len))status="SAVE FAILED";else if(compile_source(source,out))status="BUILD FAILED - SEE TERMINAL";else{built=1;status="BUILD PASS - BYTECODE READY";if(run){int rc=runbc(out,NULL,0,NULL);status=rc?"RUN FAILED - SEE TERMINAL":"RUN PASS - DETERMINISTIC";}}xpaint(d,w,gc,edit,status);}else if(interactive&&ks==0xff08){if(len){len--;edit[len]=0;}built=0;xpaint(d,w,gc,edit,"MODIFIED");}else if(interactive&&ks==0xff0d){if(len+1<cap){edit[len++]='\n';edit[len]=0;}built=0;xpaint(d,w,gc,edit,"MODIFIED");}else if(interactive&&n>0){for(int i=0;i<n&&len+1<cap;i++)if((unsigned char)b[i]>=32&&b[i]!='\x7f')edit[len++]=b[i];edit[len]=0;built=0;xpaint(d,w,gc,edit,"MODIFIED");}}else if(interactive&&e.type==4&&e.xbutton.y>=8&&e.xbutton.y<=31){int build=e.xbutton.x>=496&&e.xbutton.x<=557,run=e.xbutton.x>=566&&e.xbutton.x<=627;if(build||run){if(!studiosave(source,edit,len))status="SAVE FAILED";else if(compile_source(source,out))status="BUILD FAILED - SEE TERMINAL";else{built=1;status="BUILD PASS - BYTECODE READY";if(run){int rc=runbc(out,NULL,0,NULL);status=rc?"RUN FAILED - SEE TERMINAL":"RUN PASS - DETERMINISTIC";}}xpaint(d,w,gc,edit,status);}}}if(interactive&&built)fprintf(stderr,"studio_bytecode=%s\n",out);XFreeGC(d,gc);XDestroyWindow(d,w);XCloseDisplay(d);free(edit);return 1;}

static int runbc(const char*path,const char*out,int gui,const char*frames){FILE*f=fopen(path,"rb");if(!f){perror(path);return 1;}uint8_t h[16];if(fread(h,1,16,f)!=16||memcmp(h,"COC1",4)||h[4]!=1){fprintf(stderr,"invalid COC1 bytecode\n");fclose(f);return 2;}uint64_t n;memcpy(&n,h+8,8);if(n>1000000){fclose(f);return 2;}Ins*p=malloc((size_t)n*sizeof* p);if(!p||fread(p,sizeof*p,(size_t)n,f)!=n){free(p);fclose(f);return 2;}fclose(f);Surr st[4096],vars[256];uint8_t mem[65536]={0},declared[65536]={0},frozen[65536]={0};uint64_t budget[65536]={0},used[65536]={0},calls[1024];size_t sp=0,cp=0;for(size_t i=0;i<256;i++)vars[i]=norm(0,0);clearc(0x100018);int rc=0;uint64_t commits=0,ip=0,steps=0;
 while(ip<n&&steps++<30000000){Ins*x=&p[ip];Surr a,b,r;int cmp=0;uint64_t next=ip+1;
  switch(x->op){case OP_PUSH:if(sp==4096){rc=3;goto done;}st[sp++]=norm(x->a,x->e);if(!st[sp-1].valid){rc=4;goto done;}break;
  case OP_ADD:case OP_SUB:case OP_MUL:if(sp<2){rc=3;goto done;}b=st[--sp];a=st[--sp];if(x->op==OP_ADD)r=sadd(a,b);else if(x->op==OP_MUL)r=smul(a,b);else r=b.n==INT64_MIN?bad():sadd(a,norm(-b.n,b.e));if(!r.valid){fprintf(stderr,"surreal overflow -> unresolved\n");rc=4;goto done;}st[sp++]=r;break;
  case OP_NEG:if(!sp||st[sp-1].n==INT64_MIN){rc=4;goto done;}st[sp-1].n=-st[sp-1].n;break;
  case OP_DUP:if(!sp||sp==4096){rc=3;goto done;}st[sp]=st[sp-1];sp++;break;case OP_DROP:if(!sp){rc=3;goto done;}sp--;break;case OP_SWAP:if(sp<2){rc=3;goto done;}a=st[sp-1];st[sp-1]=st[sp-2];st[sp-2]=a;break;
  case OP_EQ:case OP_LT:case OP_GT:if(sp<2){rc=3;goto done;}b=st[--sp];a=st[--sp];if(!scmp(a,b,&cmp)){rc=4;goto done;}st[sp++]=norm(x->op==OP_EQ?cmp==0:x->op==OP_LT?cmp<0:cmp>0,0);break;
  case OP_PRINT:if(!sp){rc=3;goto done;}sprint(stdout,st[sp-1]);fputc('\n',stdout);break;
  case OP_EMIT:if(!sp){rc=3;goto done;}a=st[--sp];if(a.e||a.n<0||a.n>255){rc=4;goto done;}fputc((int)a.n,stdout);break;
  case OP_ANTENORA:if(sp==4096){rc=3;goto done;}cmp=getchar();st[sp++]=norm(cmp==EOF?-1:awarp((uint8_t)cmp),0);break;
  case OP_SOURCEBYTE:if(sp==4096){rc=3;goto done;}cmp=getchar();st[sp++]=norm(cmp==EOF?-1:(uint8_t)cmp,0);break;
  case OP_JUMP:if(x->a<0||(uint64_t)x->a>=n){rc=2;goto done;}next=(uint64_t)x->a;break;
  case OP_JZ:case OP_JNZ:if(!sp||x->a<0||(uint64_t)x->a>=n){rc=3;goto done;}a=st[--sp];if(!scmp(a,norm(0,0),&cmp)){rc=4;goto done;}if((x->op==OP_JZ&&cmp==0)||(x->op==OP_JNZ&&cmp!=0))next=(uint64_t)x->a;break;
  case OP_CALL:if(cp==1024||x->a<0||(uint64_t)x->a>=n){rc=3;goto done;}calls[cp++]=ip+1;next=(uint64_t)x->a;break;case OP_RET:if(!cp){rc=3;goto done;}next=calls[--cp];break;
  case OP_LOADV:if(x->a<0||x->a>=256||sp==4096){rc=3;goto done;}st[sp++]=vars[x->a];break;case OP_STOREV:if(x->a<0||x->a>=256||!sp){rc=3;goto done;}vars[x->a]=st[--sp];break;
  case OP_JUDECCA:if(x->a<0||x->a>=65536||x->b<1||declared[x->a]){fprintf(stderr,"judecca declaration fault address=%"PRId64"\n",x->a);rc=6;goto done;}declared[x->a]=1;budget[x->a]=(uint64_t)x->b;break;
  case OP_MLOAD:if(!sp){rc=3;goto done;}a=st[--sp];if(a.e||a.n<0||a.n>=65536){rc=4;goto done;}if(!declared[a.n]||frozen[a.n]||used[a.n]>=budget[a.n]){fprintf(stderr,"judecca access fault address=%"PRId64"\n",a.n);rc=6;goto done;}used[a.n]++;st[sp++]=norm(mem[a.n],0);if(used[a.n]==budget[a.n])frozen[a.n]=1;break;
  case OP_MSTORE:if(sp<2){rc=3;goto done;}b=st[--sp];a=st[--sp];if(a.e||a.n<0||a.n>=65536||b.e||b.n<0||b.n>255){rc=4;goto done;}if(!declared[a.n]||frozen[a.n]||used[a.n]>=budget[a.n]){fprintf(stderr,"judecca access fault address=%"PRId64"\n",a.n);rc=6;goto done;}used[a.n]++;mem[a.n]=(uint8_t)b.n;if(used[a.n]==budget[a.n])frozen[a.n]=1;break;
  case OP_PIXEL:rectc((int)x->a,(int)x->b,1,1,(uint32_t)x->c);break;case OP_RECT:rectc((int)x->a,(int)x->b,(int)x->c,(int)x->d,(uint32_t)x->k);break;
  case OP_CLEAR:clearc((uint32_t)x->a);break;case OP_CAINA:commits++;if(frames&&!frameppm(frames,commits)){perror("caina frame");rc=1;goto done;}break;case OP_HALT:goto done;default:rc=2;goto done;}ip=next;
 }
 if(steps>=30000000){fprintf(stderr,"step limit exceeded\n");rc=5;}
done: free(p);if(out&&!ppm(out)){perror(out);return 1;}if(gui&&!showx(NULL))fprintf(stderr,"no display; canvas remains available via --ppm\n");fprintf(stderr,"caina_commits=%"PRIu64" deterministic=yes steps=%"PRIu64"\n",commits,steps);return rc;}

#define CNODES 16384u
#define CEDGES 262144u
#define CMEMO 1048576u
typedef struct{uint32_t lo,ln,ro,rn,birth;}CNode;
typedef struct{CNode n[CNODES];uint32_t e[CEDGES],nn,en;const char*s;unsigned depth;int err;}CU;
typedef struct{uint64_t key;uint32_t value;uint8_t used;}CEnt;
static CEnt cleq[CMEMO],caddm[CMEMO],cmulm[CMEMO];static uint32_t cnegm[CNODES];static uint8_t cnegused[CNODES];
static uint32_t cnode(CU*u,const uint32_t*l,uint32_t ln,const uint32_t*r,uint32_t rn){if(u->nn>=CNODES||u->en+ln+rn>CEDGES){u->err=1;return UINT32_MAX;}uint32_t id=u->nn++,b=0,lo=u->en;for(uint32_t i=0;i<ln;i++){u->e[u->en++]=l[i];if(u->n[l[i]].birth>=b)b=u->n[l[i]].birth+1;}uint32_t ro=u->en;for(uint32_t i=0;i<rn;i++){u->e[u->en++]=r[i];if(u->n[r[i]].birth>=b)b=u->n[r[i]].birth+1;}u->n[id]=(CNode){lo,ln,ro,rn,b};return id;}
static void cws(CU*u){while(*u->s==' '||*u->s=='\t'||*u->s=='\r'||*u->s=='\n')u->s++;}
static uint32_t cparse(CU*u){uint32_t l[128],r[128],ln=0,rn=0;if(u->depth++>256){u->err=1;return UINT32_MAX;}cws(u);if(*u->s!='{'){u->err=1;return UINT32_MAX;}u->s++;cws(u);if(*u->s!='|')for(;;){if(ln==128){u->err=1;return UINT32_MAX;}l[ln++]=cparse(u);if(u->err)return UINT32_MAX;cws(u);if(*u->s==','){u->s++;continue;}break;}if(*u->s!='|'){u->err=1;return UINT32_MAX;}u->s++;cws(u);if(*u->s!='}')for(;;){if(rn==128){u->err=1;return UINT32_MAX;}r[rn++]=cparse(u);if(u->err)return UINT32_MAX;cws(u);if(*u->s==','){u->s++;continue;}break;}if(*u->s!='}'){u->err=1;return UINT32_MAX;}u->s++;u->depth--;return cnode(u,l,ln,r,rn);}
static CEnt*cent(CEnt*t,uint64_t key){uint32_t i=(uint32_t)((key*11400714819323198485ull)>>(64-20));for(uint32_t k=0;k<CMEMO;k++,i=(i+1)&(CMEMO-1))if(!t[i].used||t[i].key==key)return&t[i];return NULL;}
static int cle(CU*u,uint32_t x,uint32_t y,unsigned depth){if(depth>1024){u->err=1;return 0;}uint64_t key=((uint64_t)x<<32)|y;CEnt*m=cent(cleq,key);if(!m){u->err=1;return 0;}if(m->used)return(int)m->value-1;m->used=1;m->key=key;m->value=1;CNode*a=&u->n[x],*b=&u->n[y];for(uint32_t i=0;i<a->ln;i++)if(cle(u,y,u->e[a->lo+i],depth+1)){m->value=1;return 0;}for(uint32_t i=0;i<b->rn;i++)if(cle(u,u->e[b->ro+i],x,depth+1)){m->value=1;return 0;}m->value=2;return 1;}
static int cvalid(CU*u,uint32_t x,uint8_t*seen){if(seen[x])return seen[x]==2;seen[x]=1;CNode*n=&u->n[x];for(uint32_t i=0;i<n->ln;i++)if(!cvalid(u,u->e[n->lo+i],seen))return 0;for(uint32_t i=0;i<n->rn;i++)if(!cvalid(u,u->e[n->ro+i],seen))return 0;for(uint32_t i=0;i<n->ln;i++)for(uint32_t j=0;j<n->rn;j++){uint32_t l=u->e[n->lo+i],r=u->e[n->ro+j];if(!cle(u,l,r,0)||cle(u,r,l,0))return 0;}seen[x]=2;return 1;}
static __int128 cfloorpow(int64_t n,unsigned sh){if(!sh)return n;__int128 d=(__int128)1<<sh,q=n/d,r=n%d;return q-(r<0);}
static __int128 cceilpow(int64_t n,unsigned sh){if(!sh)return n;__int128 d=(__int128)1<<sh,q=n/d,r=n%d;return q+(r>0);}
static int ceval(CU*u,uint32_t x,Surr*v,uint8_t*state){if(state[x])return state[x]==2;state[x]=1;CNode*n=&u->n[x];Surr lo=bad(),hi=bad();for(uint32_t i=0;i<n->ln;i++){uint32_t q=u->e[n->lo+i];if(!ceval(u,q,v,state))return 0;int c;if(!lo.valid||!scmp(v[q],lo,&c))lo=v[q];else if(c>0)lo=v[q];}for(uint32_t i=0;i<n->rn;i++){uint32_t q=u->e[n->ro+i];if(!ceval(u,q,v,state))return 0;int c;if(!hi.valid||!scmp(v[q],hi,&c))hi=v[q];else if(c<0)hi=v[q];}for(unsigned e=0;e<=62;e++){__int128 mn=INT64_MIN,mx=INT64_MAX;if(lo.valid){mn=e>=lo.e?(__int128)lo.n*((__int128)1<<(e-lo.e))+1:cfloorpow(lo.n,lo.e-e)+1;}if(hi.valid){mx=e>=hi.e?(__int128)hi.n*((__int128)1<<(e-hi.e))-1:cceilpow(hi.n,hi.e-e)-1;}if(mn<=mx){__int128 q=mn<=0&&mx>=0?0:mn>0?mn:mx;if(q>=INT64_MIN&&q<=INT64_MAX){v[x]=norm((int64_t)q,e);state[x]=2;return v[x].valid;}}}u->err=1;return 0;}
static uint32_t cneg(CU*u,uint32_t x){if(cnegused[x])return cnegm[x];CNode*n=&u->n[x];uint32_t l[128],r[128];if(n->rn>128||n->ln>128){u->err=1;return UINT32_MAX;}for(uint32_t i=0;i<n->rn;i++)l[i]=cneg(u,u->e[n->ro+i]);for(uint32_t i=0;i<n->ln;i++)r[i]=cneg(u,u->e[n->lo+i]);uint32_t z=cnode(u,l,n->rn,r,n->ln);cnegused[x]=1;cnegm[x]=z;return z;}
static uint32_t cadd(CU*u,uint32_t x,uint32_t y){uint64_t key=((uint64_t)x<<32)|y;CEnt*m=cent(caddm,key);if(!m){u->err=1;return UINT32_MAX;}if(m->used)return m->value;CNode*a=&u->n[x],*b=&u->n[y];uint32_t ln=a->ln+b->ln,rn=a->rn+b->rn;if(ln>256||rn>256){u->err=1;return UINT32_MAX;}uint32_t l[256],r[256],q=0;for(uint32_t i=0;i<a->ln;i++)l[q++]=cadd(u,u->e[a->lo+i],y);for(uint32_t i=0;i<b->ln;i++)l[q++]=cadd(u,x,u->e[b->lo+i]);q=0;for(uint32_t i=0;i<a->rn;i++)r[q++]=cadd(u,u->e[a->ro+i],y);for(uint32_t i=0;i<b->rn;i++)r[q++]=cadd(u,x,u->e[b->ro+i]);uint32_t z=cnode(u,l,ln,r,rn);m->used=1;m->key=key;m->value=z;return z;}
static uint32_t csub(CU*u,uint32_t x,uint32_t y){return cadd(u,x,cneg(u,y));}
static uint32_t cmul(CU*u,uint32_t x,uint32_t y){uint64_t key=((uint64_t)x<<32)|y;CEnt*m=cent(cmulm,key);if(!m){u->err=1;return UINT32_MAX;}if(m->used)return m->value;CNode*a=&u->n[x],*b=&u->n[y];uint64_t ln=(uint64_t)a->ln*b->ln+(uint64_t)a->rn*b->rn,rn=(uint64_t)a->ln*b->rn+(uint64_t)a->rn*b->ln;if(ln>256||rn>256){u->err=1;return UINT32_MAX;}uint32_t l[256],r[256],q=0;for(uint32_t i=0;i<a->ln;i++)for(uint32_t j=0;j<b->ln;j++)l[q++]=csub(u,cadd(u,cmul(u,u->e[a->lo+i],y),cmul(u,x,u->e[b->lo+j])),cmul(u,u->e[a->lo+i],u->e[b->lo+j]));for(uint32_t i=0;i<a->rn;i++)for(uint32_t j=0;j<b->rn;j++)l[q++]=csub(u,cadd(u,cmul(u,u->e[a->ro+i],y),cmul(u,x,u->e[b->ro+j])),cmul(u,u->e[a->ro+i],u->e[b->ro+j]));q=0;for(uint32_t i=0;i<a->ln;i++)for(uint32_t j=0;j<b->rn;j++)r[q++]=csub(u,cadd(u,cmul(u,u->e[a->lo+i],y),cmul(u,x,u->e[b->ro+j])),cmul(u,u->e[a->lo+i],u->e[b->ro+j]));for(uint32_t i=0;i<a->rn;i++)for(uint32_t j=0;j<b->ln;j++)r[q++]=csub(u,cadd(u,cmul(u,u->e[a->ro+i],y),cmul(u,x,u->e[b->lo+j])),cmul(u,u->e[a->ro+i],u->e[b->lo+j]));uint32_t z=cnode(u,l,(uint32_t)ln,r,(uint32_t)rn);m->used=1;m->key=key;m->value=z;return z;}
static void cprint(CU*u,uint32_t x,unsigned depth){if(depth>64){fputs("...",stdout);return;}CNode*n=&u->n[x];fputc('{',stdout);for(uint32_t i=0;i<n->ln;i++){if(i)fputc(',',stdout);cprint(u,u->e[n->lo+i],depth+1);}fputc('|',stdout);for(uint32_t i=0;i<n->rn;i++){if(i)fputc(',',stdout);cprint(u,u->e[n->ro+i],depth+1);}fputc('}',stdout);}
static uint32_t cinput(CU*u,const char*s){u->s=s;uint32_t x=cparse(u);cws(u);if(*u->s)u->err=1;return x;}
static int conway_cli(int ac,char**av){if(ac<3)return 2;CU*u=calloc(1,sizeof* u);uint8_t*seen=calloc(CNODES,1);Surr*val=calloc(CNODES,sizeof*val);uint8_t*estate=calloc(CNODES,1);if(!u||!seen||!val||!estate){free(u);free(seen);free(val);free(estate);return 1;}memset(cleq,0,sizeof cleq);memset(caddm,0,sizeof caddm);memset(cmulm,0,sizeof cmulm);memset(cnegused,0,sizeof cnegused);uint32_t x=cinput(u,av[2]),y=UINT32_MAX,z=x;if(u->err)goto badin;memset(seen,0,CNODES);if(!cvalid(u,x,seen))goto badcut;if(!strcmp(av[1],"validate")||!strcmp(av[1],"birthday")||!strcmp(av[1],"value")){if(ac!=3)goto badin;}else if(!strcmp(av[1],"neg")){if(ac!=3)goto badin;z=cneg(u,x);}else{if(ac!=4)goto badin;y=cinput(u,av[3]);if(u->err)goto badin;memset(seen,0,CNODES);if(!cvalid(u,y,seen))goto badcut;if(!strcmp(av[1],"compare")){int xy=cle(u,x,y,0),yx=cle(u,y,x,0);printf("%d\n",xy?(yx?0:-1):1);free(estate);free(val);free(seen);free(u);return 0;}if(!strcmp(av[1],"add"))z=cadd(u,x,y);else if(!strcmp(av[1],"sub"))z=csub(u,x,y);else if(!strcmp(av[1],"mul"))z=cmul(u,x,y);else goto badin;}memset(seen,0,CNODES);if(u->err||z==UINT32_MAX||!cvalid(u,z,seen))goto badcut;if(!strcmp(av[1],"validate"))printf("valid=yes nodes=%u birthday=%u\n",u->nn,u->n[z].birth);else if(!strcmp(av[1],"birthday"))printf("%u\n",u->n[z].birth);else if(!strcmp(av[1],"value")){if(!ceval(u,z,val,estate))goto badcut;sprint(stdout,val[z]);fputc('\n',stdout);}else{cprint(u,z,0);printf("\nnodes=%u birthday=%u valid=yes",u->nn,u->n[z].birth);if(ceval(u,z,val,estate)){fputs(" value=",stdout);sprint(stdout,val[z]);}fputc('\n',stdout);}free(estate);free(val);free(seen);free(u);return 0;badcut:fprintf(stderr,"invalid Conway cut or resource bound\n");free(estate);free(val);free(seen);free(u);return 4;badin:fprintf(stderr,"invalid Conway syntax or command\n");free(estate);free(val);free(seen);free(u);return 2;}

static int surreal_cli(int ac,char**av){if(ac!=6){fprintf(stderr,"usage: surreal add|mul|cmp N E N E\n");return 2;}Surr a=norm(strtoll(av[2],0,0),(unsigned)strtoul(av[3],0,0)),b=norm(strtoll(av[4],0,0),(unsigned)strtoul(av[5],0,0)),r;if(!strcmp(av[1],"add"))r=sadd(a,b);else if(!strcmp(av[1],"mul"))r=smul(a,b);else if(!strcmp(av[1],"cmp")){int z;if(!scmp(a,b,&z))return 4;printf("%d\n",z);return 0;}else return 2;sprint(stdout,r);fputc('\n',stdout);return r.valid?0:4;}
static int seq(Surr a,Surr b){int c;return scmp(a,b,&c)&&c==0;}
static int selftest(void){Surr a=norm(2,2),b=norm(1,1),r=sadd(a,b),m=smul(norm(3,1),norm(-2,2));int c=9;uint64_t cases=0;if(sizeof(Ins)!=48||!r.valid||r.n!=1||r.e!=0||!m.valid||m.n!=-3||m.e!=2||!scmp(a,b,&c)||c)return 1;for(unsigned q=0;q<256;q++)if(aunwarp(awarp((uint8_t)q))!=(uint8_t)q)return 1;for(int an=-16;an<=16;an++)for(unsigned ae=0;ae<=5;ae++){a=norm(an,ae);if(!a.valid||!seq(a,norm(a.n,a.e)))return 1;for(int bn=-16;bn<=16;bn++)for(unsigned be=0;be<=5;be++){b=norm(bn,be);Surr ab=sadd(a,b),ba=sadd(b,a),am=smul(a,b),bm=smul(b,a);int abcmp,bacmp;if(!ab.valid||!ba.valid||!am.valid||!bm.valid||!seq(ab,ba)||!seq(am,bm)||!seq(sadd(a,norm(0,0)),a)||!seq(smul(a,norm(1,0)),a)||!scmp(a,b,&abcmp)||!scmp(b,a,&bacmp)||abcmp!=-bacmp)return 1;cases+=7;}}for(int an=-4;an<=4;an++)for(unsigned ae=0;ae<=3;ae++)for(int bn=-4;bn<=4;bn++)for(unsigned be=0;be<=3;be++)for(int dn=-4;dn<=4;dn++)for(unsigned de=0;de<=3;de++){a=norm(an,ae);b=norm(bn,be);Surr d=norm(dn,de),left=smul(a,sadd(b,d)),right=sadd(smul(a,b),smul(a,d));if(!left.valid||!right.valid||!seq(left,right))return 1;cases++;}printf("instruction_bytes=48 PASS\nsurreal_exact=PASS\nnormalization=PASS\ncomparison=PASS\noverflow_unresolved=PASS\nantenora_roundtrip_cases=256 PASS\ndeterminism=PASS\ndyadic_property_cases=%"PRIu64" PASS\n",cases);return 0;}
static int about(void){puts("name=Cocytus\nversion=0.2.1\nsource_extension=.coc\nbytecode=COC1\nbytecode_instruction_bytes=48\ncompiler_self_hosted=yes\nself_host_scope=canonical-cocytus-compiler-fixed-point\ncompiler_quine=stage1-equals-stage2-equals-stage3\nbootstrap_seed=bootstrap/cocytus_seed.c\nseed_origin=verified-pre-cocytus-0.7-source\nnumeric_vm=exact-finite-dyadic\nconway_scope=finite-well-founded-cuts\njudecca=declared-access-budget-freeze\nantenora=affine-byte-warp-3x-plus-1-mod-256\ncaina=deterministic-visual-commit\nptolomaea=function-entry\ngui_raster=640x400-ppm\nx11_backend=interactive-host-presentation");return 0;}
static void usage(void){fputs("Cocytus 0.2.1\ncommands:\n  about\n  compile SOURCE.coc OUT.cob\n  canonicalize FILE.cob OUT.coc\n  run FILE.cob [--ppm FILE] [--frames PREFIX] [--gui]\n  studio SOURCE.coc\n  surreal add|mul|cmp N E N E\n  conway validate|birthday|value|neg EXPR\n  conway compare|add|sub|mul EXPR EXPR\n  selftest\n",stderr);}
int main(int ac,char**av){if(ac<2){usage();return 2;}if(!strcmp(av[1],"about")&&ac==2)return about();if(!strcmp(av[1],"compile")&&ac==4)return compile_source(av[2],av[3]);if(!strcmp(av[1],"canonicalize")&&ac==4)return canonicalize(av[2],av[3]);if(!strcmp(av[1],"studio")&&ac==3)return showx(av[2])?0:1;if(!strcmp(av[1],"surreal"))return surreal_cli(ac-1,av+1);if(!strcmp(av[1],"conway"))return conway_cli(ac-1,av+1);if(!strcmp(av[1],"selftest")&&ac==2)return selftest();if(!strcmp(av[1],"run")&&ac>=3){const char*out=NULL,*frames=NULL;int gui=0;for(int i=3;i<ac;i++){if(!strcmp(av[i],"--gui"))gui=1;else if(!strcmp(av[i],"--ppm")&&i+1<ac)out=av[++i];else if(!strcmp(av[i],"--frames")&&i+1<ac)frames=av[++i];else return 2;}return runbc(av[2],out,gui,frames);}usage();return 2;}
